/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formas;

import java.awt.Color;
import java.awt.Graphics;

public class Formas_Dibujo extends javax.swing.JFrame {

    /**
     * Creates new form Formas_Dibujo
     */
    public Formas_Dibujo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formas_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formas_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formas_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formas_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formas_Dibujo().setVisible(true);
            }
        });
    }

    
    @Override
    public void paint(Graphics g){
        int i=40;
        super.paint(g);
        //mapa
        g.setColor(Color.BLACK);
        g.fillRect(30, 30, 220, 500);
        g.setColor(Color.LIGHT_GRAY);
        g.fillRect(40, 40, 200, 480);
        
        //contorno
        g.setColor(Color.GRAY);
        i=40;
        for(int j=0;j<10;j++){
            g.fillRect(i, 40, 4, 480);
            i+=20;
        }
        i=57;
        for(int j=0;j<10;j++){
            g.fillRect(i, 40, 4, 480);
            i+=20;
        }
        i=40;
        for(int j=0;j<24;j++){
            g.fillRect(40, i, 200, 4);
            i+=20;
        }
        i=57;
        for(int j=0;j<24;j++){
            g.fillRect(40, i, 200, 4);
            i+=20;
        }
        i=40;
        g.setColor(Color.white);
        //Lineas
        for(int j=0;j<11;j++){
            g.drawLine(i, 520, i, 40);
            i+=20;
        }
        i=40;
        for(int j=0;j<25;j++){
            g.drawLine(240, i, 40, i);
            i+=20;
        }
        
        //Cuadro normal------------------
        g.setColor(new Color(0, 100, 0));
        g.fillRect(121, 41, 18, 18);
        g.setColor(Color.GREEN);
        g.fillRect(124, 44, 12, 12);
        //I
        g.setColor(Color.RED);
        g.fillRect(121, 81, 18, 18);
        g.fillRect(141, 81, 18, 18);
        g.fillRect(161, 81, 18, 18);
        g.fillRect(101, 81, 18, 18);
        g.setColor(Color.PINK);
        g.fillRect(124, 84, 12, 12);
        g.fillRect(144, 84, 12, 12);
        g.fillRect(164, 84, 12, 12);
        g.fillRect(104, 84, 12, 12);
        
        //0
        g.setColor(Color.ORANGE);
        g.fillRect(121, 121, 18, 18);
        g.fillRect(141, 141, 18, 18);
        g.fillRect(121, 141, 18, 18);
        g.fillRect(141, 121, 18, 18);
        g.setColor(Color.YELLOW);
        g.fillRect(124, 124, 12, 12);
        g.fillRect(144, 144, 12, 12);
        g.fillRect(124, 144, 12, 12);
        g.fillRect(144, 124, 12, 12);       
        //L
        g.setColor(Color.MAGENTA);
        g.fillRect(121, 201, 18, 18);
        g.fillRect(141, 201, 18, 18);
        g.fillRect(101, 181, 18, 18);
        g.fillRect(101, 201, 18, 18);
        g.setColor(new Color(204, 66, 110));
        g.fillRect(124, 204, 12, 12);
        g.fillRect(144, 204, 12, 12);
        g.fillRect(104, 184, 12, 12);
        g.fillRect(104, 204, 12, 12);
        //J
        g.setColor(new Color(128, 0, 128));
        g.fillRect(121, 261, 18, 18);
        g.fillRect(141, 261, 18, 18);
        g.fillRect(141, 241, 18, 18);
        g.fillRect(101, 261, 18, 18);
        g.setColor(new Color(108, 70, 117));
        g.fillRect(124, 264, 12, 12);
        g.fillRect(144, 264, 12, 12);
        g.fillRect(144, 244, 12, 12);
        g.fillRect(104, 264, 12, 12);
        
        
    }
    
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}