package com.leviatanes.tetris;

import com.leviatanes.tetris.TetrisGame.*;

public class TetrisPanel extends javax.swing.JPanel {
    private GameArea gameArea;

    public TetrisPanel() {
        initComponents();
        this.gameHolder.setBounds(240, 12, 240, 576);
        this.gameArea = new GameArea(this.gameHolder, 10);
        this.add(gameArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameHolder = new javax.swing.JPanel();

        gameHolder.setBackground(new java.awt.Color(255, 255, 255));
        gameHolder.setMaximumSize(new java.awt.Dimension(240, 576));

        javax.swing.GroupLayout gameHolderLayout = new javax.swing.GroupLayout(gameHolder);
        gameHolder.setLayout(gameHolderLayout);
        gameHolderLayout.setHorizontalGroup(
                gameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 240, Short.MAX_VALUE));
        gameHolderLayout.setVerticalGroup(
                gameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 576, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(gameHolder, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(275, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(gameHolder, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameHolder;
    // End of variables declaration//GEN-END:variables
}
